Update restore

diff --git a/src/restore b/src/restore
--- a/src/restore
+++ b/src/restore
@@ -20,15 +20,15 @@ then
   exit 1
 fi
 
-FILES_ARCHIVE="/backups/backup_$1.tar.gz"
+#FILES_ARCHIVE="/backups/backup_$1.tar.gz"
 SQL_ARCHIVE="/backups/backup_$1.sql.bz2"
 
-if [[ ! -f $FILES_ARCHIVE ]]
-then
-  echo "The file $FILES_ARCHIVE does not exist. Aborting."
-  echo "Finished: FAILURE."
-  exit 1
-fi
+#if [[ ! -f $FILES_ARCHIVE ]]
+#then
+#  echo "The file $FILES_ARCHIVE does not exist. Aborting."
+#  echo "Finished: FAILURE."
+#  exit 1
+#fi
 
 if [[ ! -f $SQL_ARCHIVE ]]
 then
@@ -39,21 +39,21 @@ fi
 
 
 # cleanup html folder
-echo "deleting files from /var/www/html/"
-rm -R /var/www/html/*
+#echo "deleting files from /var/www/html/"
+#rm -R /var/www/html/*
 
 # restore files
-echo "restoring files from $FILES_ARCHIVE to /var/www/html"
-tar -xzf $FILES_ARCHIVE --directory="/var/www/html/"
+#echo "restoring files from $FILES_ARCHIVE to /var/www/html"
+#tar -xzf $FILES_ARCHIVE --directory="/var/www/html/"
 
 # update wp-config.php
-sed -i s/"define('DB_NAME', '.*');"/"define('DB_NAME', '$MYSQL_ENV_MYSQL_DATABASE');"/g /var/www/html/wp-config.php
-sed -i s/"define('DB_USER', '.*');"/"define('DB_USER', '$MYSQL_ENV_MYSQL_USER');"/g /var/www/html/wp-config.php
-sed -i s/"define('DB_PASSWORD', '.*');"/"define('DB_PASSWORD', '$MYSQL_ENV_MYSQL_PASSWORD');"/g /var/www/html/wp-config.php
-sed -i s/"define('DB_HOST', '.*');"/"define('DB_HOST', 'mysql:$MYSQL_PORT_3306_TCP_PORT');"/g /var/www/html/wp-config.php
+#sed -i s/"define('DB_NAME', '.*');"/"define('DB_NAME', '$MYSQL_ENV_MYSQL_DATABASE');"/g /var/www/html/wp-config.php
+#sed -i s/"define('DB_USER', '.*');"/"define('DB_USER', '$MYSQL_ENV_MYSQL_USER');"/g /var/www/html/wp-config.php
+#sed -i s/"define('DB_PASSWORD', '.*');"/"define('DB_PASSWORD', '$MYSQL_ENV_MYSQL_PASSWORD');"/g /var/www/html/wp-config.php
+#sed -i s/"define('DB_HOST', '.*');"/"define('DB_HOST', 'mysql:$MYSQL_PORT_3306_TCP_PORT');"/g /var/www/html/wp-config.php
 
 # set correct file owner
-chown -R www-data:www-data /var/www/html
+#chown -R www-data:www-data /var/www/html
 
 # restore database
 echo "restoring data from mysql dump file $SQL_ARCHIVE"
